language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - EXECUTE_CS_CHECK=true
        - TEST_COVERAGE=true
        - SERVER_VERSION=3.4.2
    - php: 7.1
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
        - SERVER_VERSION=3.4.2
    - php: 7.2
      env:
        - DEPENDENCIES=""
        - SERVER_VERSION=3.4.2
    - php: 7.2
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
        - SERVER_VERSION=3.4.2

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$SERVER_VERSION.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-$SERVER_VERSION/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --noauth &> /dev/null &

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - phpenv config-rm xdebug.ini
  - composer self-update
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer update --prefer-dist $DEPENDENCIES

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml; else ./vendor/bin/phpunit; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run; fi

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls -v; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61c75218816eebde4486
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
